# Generated by Django 4.2.7 on 2024-01-24 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата - время'),
        ),
    ]
